### ISSUE TITLE
可否用一个webdav服务，一个账户挂载多个硬盘?

### ISSUE THREAD

**Issue by Esltdk** [117503445/GoWebDAV#13]
用着很舒服的一个docker。x86 arm都可以用。
请教它可否用一个webdav服务，一个账户挂载多个硬盘? 应该怎么写docker命令？
现在使用一个账户对应一个硬盘，四个硬盘就得设置四个账户，在客户端挂载就得设置四次。

**Comment by 117503445** [comment]
目前我的确就是设置 4 次的，使用相同的账户名密码

当时我也没考虑这么多，就自己用用怎么方便怎么来。后来发现有些小问题，但是也有别人在用了，有历史包袱了，就不太好改了。

**Comment by Esltdk** [comment]
理解，先这么用着，毕竟openwrt也不会挂太多块硬盘。
最近一年发现nas普及很快，webdav的用处也变广泛，一直在找好用的docker版webdav服务，发现几乎都是只能挂载一个硬盘。你这个可以挂载多个，是比较好的了。
如果有时间或者精力的话 希望能把它修改更新一版，应该会受到更多人使用。
ps：群晖 威联通自带有webdav，docker版webdav主要是用在openwrt（或omv等不带webdav服务的nas系统）下，使之挂载硬盘+域名外网使用，支持这种方法的app客户端也变多了。

**Comment by 117503445** [comment]
嗯嗯，我觉得 <https://github.com/hacdias/webdav> 的配置文件设计就挺好的，以后本项目可以考虑在兼容旧写法的同时，使用新的写法
