### ISSUE TITLE
Docker image doesn't work with --user

### ISSUE THREAD

**Issue by namazso** [117503445/GoWebDAV#18]
Running as non-root doesn't work because `app` is in `/root`, which is inaccessible to other users

**Comment by 117503445** [comment]
I have moved the app to /workspace/gowebdav, please pull the image and try again?

**Comment by namazso** [comment]
Thanks for the quick fix, it works well enough now. I had to use --entrypoint to be able to override the port, as just adding `--port` at the end doesn't seem to work for some reason. My final commandline was this:

`podman run --rm -it --network=host --userns=host --user=979:975 --mount=type=bind,source=/mnt/data,destination=/mnt/data,ro --security-opt label=disable  --security-opt=no-new-privileges -v /var/data/gowebdav/data:/workspace/gowebdav/data:z --entrypoint ./app docker.io/117503445/go_webdav --port 8086 --dav "/data,/mnt/data,null,null,false"`
