### ISSUE TITLE
117503445大神，可以gowebdav增加https支持吗?

### ISSUE THREAD

**Issue by lpflhh** [117503445/GoWebDAV#19]
117503445大神，可以gowebdav增加https支持吗?

**Comment by 117503445** [comment]
不好意思哈，我不想添加这个功能，详情可见 <https://github.com/117503445/GoWebDAV/pull/16>

你可以使用 Nginx / Traefik 等网关来实现 https

**Comment by lpflhh** [comment]
了解了，谢谢您的回复
