### ISSUE TITLE
能否支持https

### ISSUE THREAD

**Issue by zyhibook** [117503445/GoWebDAV#3]
是否可以加入支持HTTPS
或者有支持HTTPS的配置文件示例

**Comment by zyhibook** [comment]
> 是否可以加入支持HTTPS
> 或者有支持HTTPS的配置文件示例

已解决，可以通过配置反向代理实现

**Comment by 117503445** [comment]
对的，我喜欢用 Nginx 实现 HTTPS，不给这个简单的小工具增添没有必要的额外功能
