### ISSUE TITLE
你这个是怎么运行的,老是报错

### ISSUE THREAD

**Issue by newyorkthink** [117503445/GoWebDAV#30]
![image](https://github.com/117503445/GoWebDAV/assets/87791643/22c300a6-0e98-4dad-b7df-383a5e1208d4)

**Comment by 117503445** [comment]
请按照 <https://github.com/117503445/GoWebDAV/blob/master/README_zh_CN.md#%E4%BD%BF%E7%94%A8> ，使用正确的参数调用，比如

`./gowebdav --addr 127.0.0.1 --port 8080`

你的 dav 参数格式也是错误的，请按照 README 进行修改

**Comment by 117503445** [comment]
然后就是 Linux 下，非 root 用户默认无法使用 1024 以下的端口

**Comment by Jipok** [comment]
You can't bind to a privileged port (ports less than 1024) as a non-root user.
There are various solutions:
1) Give the application the ability to bind privileged ports:
`    sudo setcap 'cap_net_bind_service=+ep' /path/to/app`
2) Temporarily change the list of privileged ports(to 0-80) for the entire system:
`    sudo sysctl -w net.ipv4.ip_unprivileged_port_start=80`
3) Permanently change the list of privileged ports(to 0-80) for the entire system
`    sudo echo 'net.ipv4.ip_unprivileged_port_start=0' > /etc/sysctl.d/50-unprivileged-ports.conf`
`    sudo sysctl --system  # To apply the setting without rebooting`
4) Run as root
5) Use an autobind: https://en.wikipedia.org/wiki/Authbind
