### ISSUE TITLE
Feature request: MinIO (S3-compatible) storage

### ISSUE THREAD

**Issue by NamesMT** [117503445/GoWebDAV#33]
First of all thanks a lot for the project, it is honestly the only project that is simple to setup and works perfectly that I could find in both JS and Go ecosystem.
It would be amazing if we have support for S3-compatible storage.

**Comment by 117503445** [comment]
Sorry, this project is just for sharing local files. Adding support for S3 will make this project heavier.

You can take a look at <https://github.com/alist-org/alist>. It has extensive support for various storage backends.

**Comment by NamesMT** [comment]
Thanks a lot!, I'll check it out.
