### ISSUE TITLE
Can not run in Windows2008r2

### ISSUE THREAD

**Issue by lantowan** [117503445/GoWebDAV#35]
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x22fcf8)
        /opt/hostedtoolcache/go/1.22.0/x64/src/runtime/sys_windows_amd64.s:75 +0
x7a fp=0x22fc80 sp=0x22fc60 pc=0x471c3a
rax     0x0
rbx     0xbfa258
rcx     0xc7fae8
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x104a2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0xbf98e0
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

**Comment by 117503445** [comment]
Sorry, Windows Server 2008 has End of support.

<https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-server-eos-faq/end-of-support-windows-server-2008-2008r2>

According to <https://github.com/golang/go/issues/57003> you can try to change go version to 1.20 and recompile.
