### ISSUE TITLE
求助帖-求nginx反向代理配置

### ISSUE THREAD

**Issue by 991548267** [117503445/GoWebDAV#37]
我反向代理我的视频文件发现无法播放。不加反向代理时可以正常播放视频。此配置使用joplin笔记可以正常同步

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_cache_bypass $http_upgrade;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header Depth $http_depth;
proxy_cache off; 
proxy_buffering off;
proxy_temp_file_write_size 2048k;

**Comment by 117503445** [comment]
我没复现出来，见 <https://github.com/117503445/gowebdav-examples>
