### ISSUE TITLE
是否考虑增加用户id和组id选项

### ISSUE THREAD

**Issue by qiz-0** [117503445/GoWebDAV#39]
docker镜像使用的是root用户,而在我的工作环境中,上传的文件会使其他用户无法删除和修改.
我尝试在docker run命令追加 -e UID=1000 -e GID=1000 但不起作用

**Comment by 117503445** [comment]
见 <https://github.com/117503445/GoWebDAV/blob/master/doc/nonroot_zh_CN.md>
