### ISSUE TITLE
能否支持arm服务器

### ISSUE THREAD

**Issue by iso-lib** [117503445/GoWebDAV#4]

**Comment by 117503445** [comment]
首先是代码没有平台相关，你直接交叉编译一份就行了
如果你是希望 117503445/go_webdav 这个镜像支持 ARM64，那么我有空的时候再去看看怎么实现这个需求

**Comment by iso-lib** [comment]
> 首先是代码没有平台相关，你直接交叉编译一份就行了
> 如果你是希望 117503445/go_webdav 这个镜像支持 ARM64，那么我有空的时候再去看看怎么实现这个需求

谢谢,,自己编译了arm64的docker镜像,原来很简单,,灰常好用.

**Comment by 117503445** [comment]
@iso-lib 现在 Docker 镜像支持 arm 了，Github Release 上也有预编译好的 arm 二进制
