### ISSUE TITLE
挂载webdav后,在客户端粘贴一个文件会消失

### ISSUE THREAD

**Issue by iso-lib** [117503445/GoWebDAV#5]
docker安装的go-webdav,配置已打开true
并用nginx代理转发端口到443,并套上https
安卓客户端NMM
挂载webdav,,查看
从本地复制一个文件
在挂载目录粘贴
会显示一个0KB文件
刷新一下,,文件就消失了.
挂载目录已权限777,,用户改为了nobody

**Comment by 117503445** [comment]
我也安装了 NMM 文件浏览器,进行了你的操作,我这里没有问题.你检查一下这几个点

1. 

比如说,电脑的ip是 192.168.1.2,把 D:/mydir 挂载在了 /public 下面

此时,你在 NMM 中输入的 WebDAV 路径 应该是 http://192.168.1.2/public 而不是 http://192.168.1.2

2.

在浏览器中打开 WebDAV 服务端口,是否能进行正常的文件增删改查

3.

目测 Nginx 不会引入问题, 你可以尝试不使用 HTTPS, NMM 直接使用 HTTP 连接有没有问题.

**Comment by iso-lib** [comment]
> 我也安装了 NMM 文件浏览器,进行了你的操作,我这里没有问题.你检查一下这几个点
> 
> 
> 比如说,电脑的ip是 192.168.1.2,把 D:/mydir 挂载在了 /public 下面
> 
> 此时,你在 NMM 中输入的 WebDAV 路径 应该是 http://192.168.1.2/public 而不是 http://192.168.1.2
> 
> 
> 在浏览器中打开 WebDAV 服务端口,是否能进行正常的文件增删改查
> 
> 
> 目测 Nginx 不会引入问题, 你可以尝试不使用 HTTPS, NMM 直接使用 HTTP 连接有没有问题.

我是在甲骨文vps上安装的docker
docker run -itd \
 --name go_webdav \
 -v /media/tr/complete:/root/dir1 \
 -e dav="/webdav,/root/dir1,dede,dede1979,true" \
 -p 37717:80 \
 --restart=always \
 117503445/go_webdav:latest

nginx配置是
server {
    listen 443 ssl;
    server_name  dj.xxxxx.xyz;
    ssl_certificate   /ssl/1_dj.xxxxx.xyz_bundle.crt;
    ssl_certificate_key  /ssl/2_dj.xxxxx.xyz.key;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

  #charset koi8 - r;
   #access_log  logs / host.access.log  main;

 location / {
            proxy_pass http://127.0.0.1:37717;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host:$server_port; 
            proxy_set_header X-Real-IP $remote_addr; 
            proxy_redirect http://$host https://$host:$server_port;
        }
}

nmm挂载url就是https://dj.xxxxxx.xyz/webdav
应该没啥问题啊.
访问看电影,下载是没问题,,就是不能增删改.

**Comment by 117503445** [comment]
这不是 bug,这是 feature ....

第 5 个参数 true 的意思就是 readonly = True, 你改成 False 就能支持增删改了

**Comment by iso-lib** [comment]
> 这不是 bug,这是 feature ....
> 
> 第 5 个参数 true 的意思就是 readonly = true, 你改成 false 就能支持增删改了

破案了,,谢谢大佬,,没仔细看文档,,其实文档写得那么清楚
轮子很好用.

**Comment by 117503445** [comment]
帮到忙的话, 给个 star 呗 :)
