### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Noahsarker** [117503445/GoWebDAV#6]
如果配置里 目录配成/ 根目录的话，web端只能访问，不能点击进入子目录

另外web能否支持移动文件

**Comment by 117503445** [comment]
1. 没 get 到你的意思.. 

我在测试的时候，使用下面的语句，是能正常操作 镜像内文件系统 根目录 的

`docker run -e dav="/dav,/,null,null,false" -p 8000:80  --rm 117503445/go_webdav`

要不你也贴一下 启动配置

2. 这个前端我是直接用 `https://github.com/dom111/webdav-js` 的，应该不会考虑在 web 端进行功能增删了。你可以使用其他支持 WebDAV 协议的客户端来完成移动文件的操作。
