### ISSUE TITLE
有没有arm的？

### ISSUE THREAD

**Issue by liang-0131** [117503445/GoWebDAV#7]
arm二进制

**Comment by 117503445** [comment]
最近有点忙，你可以自己编译一份，应该没啥坑

有空了，我研究一下怎么用 Github Action 发布多架构的二进制包和 Docker 镜像

**Comment by liang-0131** [comment]
编译成功了，可以用

**Comment by 117503445** [comment]
> arm二进制

现在已经可以从 Release 下载编译好的 arm 二进制了
