### ISSUE TITLE
使用GoWebDAV的几个疑问

### ISSUE THREAD

**Issue by xjl456852** [117503445/GoWebDAV#8]
你好,高性能的gowebdav服务器我一直在寻找,很高兴能看到这种高性能服务器.
但是我有几个疑问:
第一:
如何使用raidrive或者windows自带的映射网络驱动器添加webdav映射.
我是用raidrive映射webdav时,提示我返回的是html页面,不是webdav地址.我只能通过浏览器访问. 不知道如何通过系统文件的方式访问.
第二:
我通过浏览器访问设置了密码的webdav服务, 提示看到了/dav1链接,点进去之后提示username wrong or password wrong
,但是也没有输入用户名和密码的地方. 我设置了用户名和密码为空后,到时能看到一闪而过的用户名和密码输入框.然后就显示出了文件.
第三:
如果我的密码中有特殊字符, 我们知道特殊字符做密码会更安全, 如果密码中本来就有逗号,分号, 这种复杂的密码,该如何添加?
再次感谢您贡献如此有前景的服务器,希望他越来越好.辛苦了

**Comment by 117503445** [comment]
1. 这个是几年前写的了。从现在的角度看，这个小项目其实只是对 `golang.org/x/net/webdav` 库的封装而已。所以说 GoWebDAV 只是相比 Apache 这些，依赖少，所以内存占用更少而已。速度的话，"2.5G 及以上带宽" "不稳定的广域网络环境" 等场景都是没测试、更没有优化的。

但是 GoWebDAV 的一个设计理念就是对个人来说用着方便。一行 docker run ，就能快速的把本地多个路径都用 WebDAV 协议暴露出来。

2. 目前每个子目录下都是支持 WebDAV 协议的，但是第一层根目录下没有支持 WebDAV。所以你可以试试挂载 /dav1 。这个问题我之前想到过，后来忘了，以后有空修。

3. 设置密码后，按道理会用 Basic Auth 的形式触发浏览器弹窗，要求输入用户名和密码。可能是浏览器弹窗设置...? 我没啥思路，也不知道怎么复现。你可以发一下 GoWebDAV 配置、浏览器版本之类的。

4. 是不支持的。因为 GoWebDAV 的特点就在于用着方便，能一行 docker run 就跑起来，所以就用了 dav 环境变量的方式。也想过用 yaml 配置文件，但是这样就比较复杂，而且现在已经有人用 dav 环境变量了(历史包袱)，又觉得反正现在这样也能跑，就懒得改了。

不过虽然 `,` 和 `;` 不能用，你还能用其他 `!` 之类的特殊符号。而且就算不用特殊符号，足够长的大小写字母口令也能保证安全性，毕竟指数的威力比底数大。

**Comment by 117503445** [comment]
比较奇怪，同样的 Edge 版本，我这里可以的，你要不换成 Edge 的 InPrivate 隐私模式试试看

![屏幕截图 2022-04-14 221129](https://user-images.githubusercontent.com/21152034/163410424-4a0d2dba-df49-4a96-969b-f58750f9663b.png)

我记得以前我用 RaiDrive 成功映射过，等我有空了再试试

**Comment by xjl456852** [comment]
隐私模式可以出现弹框,可能跟Basic Auth这种验证方式有关.
Raidrive这种添加映射时,提示返回的html,无法进行映射.

**Comment by 117503445** [comment]
![image](https://user-images.githubusercontent.com/21152034/166104594-b6099e48-789a-4ebd-8d28-c082ee53aec7.png)
![image](https://user-images.githubusercontent.com/21152034/166104601-d8b227be-c9aa-41ab-9a80-482b16c8913f.png)
![image](https://user-images.githubusercontent.com/21152034/166104612-dd1ac999-1abb-47a1-8613-e1e48fab92a3.png)
![image](https://user-images.githubusercontent.com/21152034/166104635-ce9d3389-6b32-4e1a-8089-1f98e48e949a.png)


我这里是可以使用 Raidrive 的，你可以把你的 Raidrive 配置发给我，让我复现一下
